name: CI
on:
  push:
    branches: [ master, '@qbane/dev' ]
  # pull_request:
  #   branches: [ master ]
jobs:
  detectonly:
    name: Detect use of .only
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Detect use of .only
        run: |
          grep -rq --include '*.spec.js' \.only\( . && echo 'You have .only() in your tests!' && exit 1
          exit 0
  default:
    name: "Default"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Default
        run: |
          npm install
          sh setup.sh
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          cd ..
          source ./emsdk/emsdk_env.sh
          cd emscriptenbuild
          ./build.sh Debug
          cd ..
          set -e
          npm run test
          npm run test-browser
          ./preparepublishnpm.sh  
          PACKAGEFILE=`npm pack | tail -n 1`
          tar -xvzf $PACKAGEFILE
          rm test-browser/lg2.*
          echo "run browser tests with npm package"
          cp package/lg2.* test-browser/
          npm run test-browser
      - uses: actions/upload-artifact@v2
        with:
          name: wasm-git-dist
          path: '*.tgz'
  asyncify:
    name: Asyncify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Default
        run: |
          npm install
          sh setup.sh
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          cd ..
          source ./emsdk/emsdk_env.sh
          cd emscriptenbuild
          ./build.sh Debug-async
          cd ..
          set -e
          npm run test-browser-async
          ./preparepublishnpm.sh  
          PACKAGEFILE=`npm pack | tail -n 1`
      - uses: actions/upload-artifact@v2
        with:
          name: wasm-git-dist-asyncify
          path: '*.tgz'
